<?php
/** @var App\Blocks\ChampionshipBlock $this */
?>

<main class="content championship">
    <table class="championship__main-table main-table">
        <caption class="championship__caption main-table__caption">The championships from the entire world</caption>
        <tr class="main-table__row main-table__row_header">
            <?php foreach ($this->getHeader() as $header): ?>
                <td class="championship__cell main-table__cell"><?= $header ?></td>
            <?php endforeach; ?>
        </tr>
        <?php foreach ($this->getContent() as $content => $cell): ?>
            <tr class="championship__row main-table__row">
                <?php foreach ($cell as $subCell): ?>
                    <td class="championship__cell main-table__cell"><?= $subCell ?></td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
    </table>
</main>
