<?php
/** @var App\Blocks\ChampionshipBlock $this */
?>

<main class="content championship">
    <table class="championship__main-table main-table">
        <caption class="championship__caption main-table__caption">The championships from the entire world</caption>
        <tr class="main-table__row main-table__row_header">
            <?php foreach ($this->getHeader() as $header): ?>
                <td class="championship__cell main-table__cell"><?= $header ?></td>
            <?php endforeach; ?>
        </tr>
        <?php foreach ($this->getContent() as $content => $cell): ?>
            <tr class="championship__row main-table__row">
                <form class="delete_row" method="get" action="/championship/delete">
                    <input name="id" type="hidden" value="<?= $cell['championship_id'] ?>">
                    <?php foreach ($cell as $subCell): ?>
                        <td class="championship__cell main-table__cell"><?= $subCell ?></td>
                    <?php endforeach; ?>
                    <td class="button"><button class="delete">delete</button></td>
                </form>
            </tr>
        <?php endforeach; ?>
    </table>

    <form class="adding-form" method="post" action="/championship/add">
        <p class="adding-form__title">Championship name:</p>
        <input class="adding-form__input" name="name" type="text">
        <p class="adding-form__title">Country-holder:</p>
        <input class="adding-form__input" name="country_id" type="text">
        <p class="adding-form__title">Begin date:</p>
        <input class="adding-form__input" name="begin_date" type="date">
        <p class="adding-form__title">Close date:</p>
        <input class="adding-form__input" name="end_date" type="date">
        <button>go</button>
    </form>
</main>
