<?php
/** @var App\Blocks\ClubBlock $this */
?>

<main class="content">
    <table class="club-table">
        <caption class="club-table__caption">The player's info table</caption>
        <tr class="club-table__row club-table__row_header">
            <?php foreach ($this->getHeader() as $header): ?>
                <td class="club-table__cell"><?= $header ?></td>
            <?php endforeach; ?>
        </tr>
        <?php foreach ($this->getContent() as $content => $cell): ?>
            <tr class="club-table__row">
                <?php foreach ($cell as $subCell): ?>
                    <td class="club-table__cell"><?= $subCell ?></td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
    </table>

    <form class="adding-form" method="post" action="/club/add">
        <p class="adding-form__title">Club name:</p>
        <input class="adding-form__input" name="name" type="text">
        <button>go</button>
    </form>

    <form class="changing-form" method="get" action="/club/change">
        <p class="changing-form__title">ID to change:</p>
        <input class="changing-form__input" name="id" type="number">
        <button>go</button>
    </form>
</main>