<?php
/** @var App\Blocks\CountryBlock $this */
?>

<main class="content">
    <table>
        <?php foreach ($this->getContent() as $content => $cell): ?>
            <tr class="table__row">
                <?php foreach ($cell as $subCell): ?>
                    <td class="table__cell"><?= $subCell ?></td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
    </table>
</main>