<?php
/** @var App\Blocks\HomeBlock $this */
?>

<main class="content home">
    <h1 class="home__main-header">Welcome to the home page!</h1>
    <h2 class="home__header">Recent news:</h2>
    <?php foreach ($this->getContent() as $data => $datum): ?>
            <?php foreach ($datum as $subDatum): ?>
                <p class="home__paragraph"><?= $subDatum ?></p>
            <?php endforeach; ?>
    <?php endforeach; ?>
</main>