<?php
/** @var App\Blocks\BlockParent $this */
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>MVC</title>
    <link rel="stylesheet" href="<?= "/css/styles/common/common.css" ?>">
    <?php foreach ($this->includedStyles as $style): ?>
            <link rel="stylesheet" href="<?php echo $style; ?>">
        <?php endforeach; ?>
</head>
<body>
    <header class="header">
        <h4 class="general-title">The best site ever existed</h4>
    </header>
    <?php include $this->includedFileName; ?>
    <footer class="footer">
        <p class="general-text">All rights are protected by nothing</p>
    </footer>
</body>
</html>
